### ISSUE TITLE
New data

### ISSUE THREAD

**Issue by mikekestemont** [emanjavacas/bntl#1]
We need a mechanism to upload/change new or existing entries by uploading bibliographic files through the browser. Should use a key (or full authentication) to ensure safety and provide a log file to signal errors. Ideally, the system fails graciously.

**Comment by emanjavacas** [comment]
I am working on an upload system (it was tricky to get it to index on the gpu running alongside the asynchronous web server, but it seems to be working now), I'll implement a authorization method with a single password (no user login) to protect certain routes. 

With respect to changing entries, I've argued in other issues as well that I think it's not a good idea, since any time there's an issue with the application it will be impossible to recreate it and the changes will be lost. Uploading documents should be fine, if at some point something needs out, I'd say we can reindex the whole database with the newest version (the whole indexing process is taking now about 30 minutes - including vectorization).

**Comment by emanjavacas** [comment]
done
