### ISSUE TITLE
Title descriptions

### ISSUE THREAD

**Issue by mikekestemont** [emanjavacas/bntl#13]
The records now have a “titelbeschrijving” which is copied from T1 in the RIS-code. This means that the description (which represents the record in the overview/list) now, is identical to the description in the old system. Converting to the new system, uniformity is one of our main goals (in contrast to the old system where numerous “exceptions” were made and different guidelines were used by different people = not uniform). We were wondering if it is possible to “build” a new titelbeschrijving from the building blocks extracted in the RIS-code, in order to gain a uniformity. (However, the T1-string should be converted as well in order for us to “clean-up” records, but not as the main title of the record.) See: https://bntl.flw.uantwerpen.be/item?doc_id=66d03bfcd27e1c0baee562db (authors not correct, Title not correct)

**Comment by emanjavacas** [comment]
Good, So far I've just trying to do my best to get a title string. I think the best is that your data curators prepare a document establishing what fields I can expect (necessary fields, optional fields, ideally also the type of field - I've made assumptions which can be seen on bntl/models.py), and what I should use to visualize items.

I can't see the link you send anymore, since the ids change every time I reindex (which is happening a lot during development). This actually made me think that it could be a bad idea to rely on generated ids, because people may want to find the record back on the same link. So maybe you guys can find a way of providing unique document ids along with the records. Let me know what you think.
